"""first2 commit

Revision ID: 0cc0a84cb73f
Revises: a790f380bc6d
Create Date: 2023-09-24 00:46:57.846008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc0a84cb73f'
down_revision = 'a790f380bc6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户id'),
    sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
    sa.Column('gender', sa.String(length=20), nullable=True, comment='性别'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='位置'),
    sa.Column('level', sa.String(length=20), nullable=True, comment='学业水平'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='邮箱'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='参与状态'),
    sa.Column('is_person_questionare', sa.Boolean(), nullable=True, comment='是否完成问卷'),
    sa.Column('is_mental_questionare', sa.Boolean(), nullable=True, comment='是否完成问卷'),
    sa.Column('is_read_audio', sa.Boolean(), nullable=True, comment='是否语音录制'),
    sa.Column('is_read_video', sa.Boolean(), nullable=True, comment='是否视频录制'),
    sa.Column('is_interview_audio', sa.Boolean(), nullable=True, comment='是否语音面试录制'),
    sa.Column('is_interview_video', sa.Boolean(), nullable=True, comment='是否视频面试录制'),
    sa.Column('mental_status', sa.String(length=20), nullable=True, comment='心理状态'),
    sa.Column('is_send_mail', sa.Boolean(), nullable=True, comment='是否发送邮件'),
    sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='最后一次更新时间'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    comment='前端用户表'
    )
    op.create_index(op.f('ix_front_users_user_id'), 'front_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_front_users_user_id'), table_name='front_users')
    op.drop_table('front_users')
    # ### end Alembic commands ###
