"""使用basemode

Revision ID: 10695c426dbc
Revises: 0c512f467a01
Create Date: 2023-09-24 17:19:30.073571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10695c426dbc'
down_revision = '0c512f467a01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
