"""first commit

Revision ID: 146b0ba34d04
Revises: 515f9d3af451
Create Date: 2024-01-25 13:37:24.775183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '146b0ba34d04'
down_revision = '515f9d3af451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmdb_desc',
    sa.Column('cmdb_desc_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('cmdb_desc_id'),
    comment='CMDB具体属性表'
    )
    op.create_index(op.f('ix_cmdb_desc_cmdb_desc_id'), 'cmdb_desc', ['cmdb_desc_id'], unique=False)
    op.create_table('cmdb_record',
    sa.Column('cmdb_record_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('cmdb_record_id'),
    comment='CMDB数据记录表'
    )
    op.create_index(op.f('ix_cmdb_record_cmdb_record_id'), 'cmdb_record', ['cmdb_record_id'], unique=False)
    op.create_table('cmdb_type',
    sa.Column('cmdb_type_id', sa.BigInteger(), nullable=False),
    sa.Column('cmdb_type_name', sa.String(length=100), nullable=False),
    sa.Column('cmdb_type_parent_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('cmdb_type_id'),
    comment='CMDB类型表'
    )
    op.create_index(op.f('ix_cmdb_type_cmdb_type_id'), 'cmdb_type', ['cmdb_type_id'], unique=False)
    op.create_table('menu',
    sa.Column('menu_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_name', sa.String(length=20), nullable=False),
    sa.Column('menu_flag', sa.String(length=20), nullable=False),
    sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='最后一次更新时间'),
    sa.PrimaryKeyConstraint('menu_id'),
    comment='菜单表'
    )
    op.create_index(op.f('ix_menu_menu_id'), 'menu', ['menu_id'], unique=False)
    op.create_table('model_front_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_user', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_user', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), nullable=True, comment='删除标识：0-正常 1-已删除'),
    sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
    sa.Column('gender', sa.String(length=20), nullable=True, comment='性别'),
    sa.Column('age', sa.String(length=4), nullable=True, comment='年龄'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='位置'),
    sa.Column('level', sa.String(length=20), nullable=True, comment='学业水平'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='邮箱'),
    sa.Column('is_active', sa.String(length=20), nullable=True, comment='参与状态'),
    sa.Column('is_person_questionare', sa.String(length=20), nullable=True, comment='是否完成问卷'),
    sa.Column('is_mental_questionare', sa.String(length=20), nullable=True, comment='是否完成问卷'),
    sa.Column('is_read_audio', sa.String(length=20), nullable=True, comment='是否语音录制'),
    sa.Column('is_read_video', sa.String(length=20), nullable=True, comment='是否视频录制'),
    sa.Column('is_interview_audio', sa.String(length=20), nullable=True, comment='是否语音面试录制'),
    sa.Column('is_interview_video', sa.String(length=20), nullable=True, comment='是否视频面试录制'),
    sa.Column('mental_status', sa.String(length=20), nullable=True, comment='心理状态'),
    sa.Column('is_send_mail', sa.String(length=20), nullable=True, comment='是否发送邮件'),
    sa.PrimaryKeyConstraint('id'),
    comment='前端用户表'
    )
    op.create_table('model_question_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_user', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_user', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), nullable=True, comment='删除标识：0-正常 1-已删除'),
    sa.Column('qestion_type', sa.String(length=20), nullable=True, comment='问题类型'),
    sa.Column('text_content', sa.String(length=200), nullable=True, comment='问题内容'),
    sa.Column('emotion_type', sa.String(length=20), nullable=True, comment='情感类型'),
    sa.Column('other', sa.String(length=200), nullable=True, comment='其他'),
    sa.Column('qestion_status', sa.String(length=200), nullable=True, comment='问题状态'),
    sa.PrimaryKeyConstraint('id'),
    comment='问题记录表'
    )
    op.create_table('model_questionaire',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_user', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_user', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), nullable=True, comment='删除标识：0-正常 1-已删除'),
    sa.Column('questionnaire_name', sa.String(length=200), nullable=True, comment='问卷名称'),
    sa.Column('questionnaire_type', sa.String(length=200), nullable=True, comment='问卷类型'),
    sa.Column('questionnaire_beizhu', sa.String(length=200), nullable=True, comment='文件类型'),
    sa.Column('questionnaire_path', sa.String(length=200), nullable=True, comment='问卷路径'),
    sa.Column('questionnaire_file_name', sa.String(length=200), nullable=True, comment='问卷保存名称'),
    sa.Column('questionnaire_status', sa.String(length=200), nullable=True, comment='问卷状态'),
    sa.Column('other', sa.String(length=200), nullable=True, comment='其他'),
    sa.PrimaryKeyConstraint('id'),
    comment='问卷管理'
    )
    op.create_table('operate_records',
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('operate_username', sa.String(length=20), nullable=False, comment='操作的用户'),
    sa.Column('operate_time', sa.DateTime(), nullable=True, comment='操作的时间'),
    sa.Column('operate_ip', sa.String(length=20), nullable=False, comment='操作的IP'),
    sa.Column('operate_type', sa.String(length=10), nullable=False, comment='操作类型'),
    sa.Column('operate_object', sa.String(length=30), nullable=False, comment='操作的对象'),
    sa.Column('operate_detail', sa.String(length=200), nullable=True, comment='操作的具体信息'),
    sa.PrimaryKeyConstraint('record_id'),
    comment='数据操作记录表'
    )
    op.create_index(op.f('ix_operate_records_operate_username'), 'operate_records', ['operate_username'], unique=False)
    op.create_index(op.f('ix_operate_records_record_id'), 'operate_records', ['record_id'], unique=False)
    op.create_table('permission',
    sa.Column('perm_id', sa.BigInteger(), nullable=False),
    sa.Column('perm_name', sa.String(length=20), nullable=False),
    sa.Column('perm_interface', sa.String(length=100), nullable=False),
    sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='最后一次更新时间'),
    sa.PrimaryKeyConstraint('perm_id'),
    comment='权限表'
    )
    op.create_index(op.f('ix_permission_perm_id'), 'permission', ['perm_id'], unique=False)
    op.create_table('role',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.Column('role_desc', sa.String(length=100), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='最后一次更新时间'),
    sa.PrimaryKeyConstraint('role_id'),
    comment='角色表'
    )
    op.create_index(op.f('ix_role_role_id'), 'role', ['role_id'], unique=False)
    op.create_table('role_menu',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('menu_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='角色和菜单关联表'
    )
    op.create_index(op.f('ix_role_menu_id'), 'role_menu', ['id'], unique=False)
    op.create_table('role_perm',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('perm_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='角色和权限关联表'
    )
    op.create_index(op.f('ix_role_perm_id'), 'role_perm', ['id'], unique=False)
    op.create_table('role_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='角色和用户关联表'
    )
    op.create_index(op.f('ix_role_user_id'), 'role_user', ['id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户id'),
    sa.Column('username', sa.String(length=20), nullable=False, comment='登陆用户名'),
    sa.Column('nick_name', sa.String(length=20), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=200), nullable=True, comment='头像'),
    sa.Column('email', sa.String(length=30), nullable=False, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=200), nullable=False, comment='加密后的密码'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='最后一次更新时间'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    comment='用户表'
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('model_file_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_user', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_user', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), nullable=True, comment='删除标识：0-正常 1-已删除'),
    sa.Column('file_name', sa.String(length=200), nullable=True, comment='文件名称'),
    sa.Column('file_type', sa.String(length=200), nullable=True, comment='文件类型'),
    sa.Column('file_time', sa.String(length=200), nullable=True, comment='文件时长'),
    sa.Column('file_url', sa.String(length=200), nullable=True, comment='文件url'),
    sa.Column('file_path', sa.String(length=200), nullable=True, comment='文件保存路径'),
    sa.Column('file_path_name', sa.String(length=200), nullable=True, comment='文件名称'),
    sa.Column('file_status', sa.String(length=200), nullable=True, comment='文件状态'),
    sa.Column('other', sa.String(length=200), nullable=True, comment='其他'),
    sa.Column('model_front_users_id', sa.Integer(), nullable=True, comment='前端用户id'),
    sa.Column('model_question_records_id', sa.Integer(), nullable=True, comment='对应的问题id'),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True, comment='对应的问卷id'),
    sa.ForeignKeyConstraint(['model_front_users_id'], ['model_front_users.id'], ),
    sa.ForeignKeyConstraint(['model_question_records_id'], ['model_question_records.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['model_questionaire.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文件存取记录表'
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('model_file_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_user_id'), table_name='role_user')
    op.drop_table('role_user')
    op.drop_index(op.f('ix_role_perm_id'), table_name='role_perm')
    op.drop_table('role_perm')
    op.drop_index(op.f('ix_role_menu_id'), table_name='role_menu')
    op.drop_table('role_menu')
    op.drop_index(op.f('ix_role_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_perm_id'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_operate_records_record_id'), table_name='operate_records')
    op.drop_index(op.f('ix_operate_records_operate_username'), table_name='operate_records')
    op.drop_table('operate_records')
    op.drop_table('model_questionaire')
    op.drop_table('model_question_records')
    op.drop_table('model_front_users')
    op.drop_index(op.f('ix_menu_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_cmdb_type_cmdb_type_id'), table_name='cmdb_type')
    op.drop_table('cmdb_type')
    op.drop_index(op.f('ix_cmdb_record_cmdb_record_id'), table_name='cmdb_record')
    op.drop_table('cmdb_record')
    op.drop_index(op.f('ix_cmdb_desc_cmdb_desc_id'), table_name='cmdb_desc')
    op.drop_table('cmdb_desc')
    # ### end Alembic commands ###
