"""first commit

Revision ID: 2b493c875832
Revises: 146b0ba34d04
Create Date: 2024-03-05 21:09:18.070898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b493c875832'
down_revision = '146b0ba34d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('users', sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户id'))
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False, comment='登陆用户名'))
    op.add_column('users', sa.Column('nick_name', sa.String(length=20), nullable=True, comment='昵称'))
    op.add_column('users', sa.Column('avatar', sa.String(length=200), nullable=True, comment='头像'))
    op.add_column('users', sa.Column('email', sa.String(length=30), nullable=False, comment='邮箱'))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=200), nullable=False, comment='加密后的密码'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'))
    op.add_column('users', sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'))
    op.add_column('users', sa.Column('update_time', sa.DateTime(), nullable=True, comment='最后一次更新时间'))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_table_comment(
        'users',
        '用户表',
        existing_comment=None,
        schema=None
    )
    op.drop_column('users', 'name')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_table_comment(
        'users',
        existing_comment='用户表',
        schema=None
    )
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_column('users', 'update_time')
    op.drop_column('users', 'creat_time')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'nick_name')
    op.drop_column('users', 'username')
    op.drop_column('users', 'user_id')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
