"""生成其他表2

Revision ID: 515f9d3af451
Revises: c4d08edb9c1d
Create Date: 2023-10-17 18:25:18.394826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515f9d3af451'
down_revision = 'c4d08edb9c1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_file_records', sa.Column('questionnaire_id', sa.Integer(), nullable=True, comment='对应的问卷id'))
    op.create_foreign_key(None, 'model_file_records', 'model_questionaire', ['questionnaire_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_file_records', type_='foreignkey')
    op.drop_column('model_file_records', 'questionnaire_id')
    # ### end Alembic commands ###
