"""first4 commit

Revision ID: 85ebfb24ed1a
Revises: f98dea4d4c2d
Create Date: 2023-09-24 17:11:56.141210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85ebfb24ed1a'
down_revision = 'f98dea4d4c2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_front_users_user_id', table_name='front_users')
    op.drop_column('front_users', 'is_delete')
    op.drop_column('front_users', 'creat_time')
    op.drop_column('front_users', 'user_id')
    op.drop_column('front_users', 'update_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_users', sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='最后一次更新时间'))
    op.add_column('front_users', sa.Column('user_id', mysql.VARCHAR(length=50), nullable=False, comment='用户id'))
    op.add_column('front_users', sa.Column('creat_time', mysql.DATETIME(), nullable=True, comment='创建时间'))
    op.add_column('front_users', sa.Column('is_delete', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='删除标识：0-正常 1-已删除'))
    op.create_index('ix_front_users_user_id', 'front_users', ['user_id'], unique=False)
    # ### end Alembic commands ###
