"""生成其他表

Revision ID: 8a253dac2ef5
Revises: cfdacf635343
Create Date: 2023-10-03 16:35:59.826307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a253dac2ef5'
down_revision = 'cfdacf635343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_file_records', sa.Column('file_path', sa.String(length=200), nullable=True, comment='文件保存路径'))
    op.add_column('model_file_records', sa.Column('file_path_name', sa.String(length=200), nullable=True, comment='文件名称'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_file_records', 'file_path_name')
    op.drop_column('model_file_records', 'file_path')
    # ### end Alembic commands ###
