"""生成其他表2

Revision ID: c4d08edb9c1d
Revises: d5e4e4475500
Create Date: 2023-10-03 16:37:58.973664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d08edb9c1d'
down_revision = 'd5e4e4475500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
