"""生成其他表

Revision ID: cfdacf635343
Revises: 50ac5ccbe564
Create Date: 2023-10-03 14:30:40.277208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdacf635343'
down_revision = '50ac5ccbe564'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_questionaire', sa.Column('questionnaire_file_name', sa.String(length=200), nullable=True, comment='问卷保存名称'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_questionaire', 'questionnaire_file_name')
    # ### end Alembic commands ###
