"""生成其他表

Revision ID: d5e4e4475500
Revises: 8a253dac2ef5
Create Date: 2023-10-03 16:37:22.743570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e4e4475500'
down_revision = '8a253dac2ef5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
