"""first3 commit

Revision ID: f98dea4d4c2d
Revises: dee587309fee
Create Date: 2023-09-24 17:07:58.426033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f98dea4d4c2d'
down_revision = 'dee587309fee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_users', sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户id'))
    op.add_column('front_users', sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'))
    op.alter_column('front_users', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='最后一次更新时间',
               existing_comment='更新时间',
               existing_nullable=True)
    op.create_index(op.f('ix_front_users_user_id'), 'front_users', ['user_id'], unique=False)
    op.drop_column('front_users', 'create_user')
    op.drop_column('front_users', 'update_user')
    op.drop_column('front_users', 'id')
    op.drop_column('front_users', 'create_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_users', sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'))
    op.add_column('front_users', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='主键ID'))
    op.add_column('front_users', sa.Column('update_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='更新人'))
    op.add_column('front_users', sa.Column('create_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='创建人'))
    op.drop_index(op.f('ix_front_users_user_id'), table_name='front_users')
    op.alter_column('front_users', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_comment='最后一次更新时间',
               existing_nullable=True)
    op.drop_column('front_users', 'creat_time')
    op.drop_column('front_users', 'user_id')
    # ### end Alembic commands ###
